// Build script for VKify16.
//
// Concatenates and minifies the themepack's modular JS (res/js/**) into a
// single IIFE bundle at res/js/dist/vkify16.bundle.js.
//
// core/vkify.js is NOT bundled: it loads non-deferred in @layout.latte so
// that synchronous consumers (core/settings-config.js, i18n/localizator.js,
// and the inline vkifylocalize call) see window.vkify immediately. All
// bundled modules are deferred and therefore execute after that script, so
// they can safely reference window.vkify at runtime.
// See .windsurf/plans/vkify16-js-bundling-fcb7b6.md for the full rationale.

import * as esbuild from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import { templateHtmlMinify } from './tools/template-html-minify.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const jsRoot = path.join(__dirname, 'res', 'js');
const outFile = path.join(jsRoot, 'dist', 'vkify16.bundle.js');

// Load order, relative to res/js/.
const modules = [
    'utils/modal-content-fetcher.js',

    'ui/loader-utils.js',
    'ui/textarea-autosize.js',
    'ui/message-box-overrides.js',

    'ui/sidebar-affix.js',
    'ui/custom-select.js',
    'ui/tab-slider.js',
    'ui/tooltips-simple.js',
    'ui/form-modal.js',
    'ui/notifications-popup.js',
    'ui/search-fasttips.js',

    'compat/player-stub.js',

    'ui/search.js',
    'ui/music-popup.js',
    'ui/media-modals.js',
    'ui/graffiti.js',

    'features/attachment-picker.js',
    'features/wall.js',
    'features/player.js',

    'features/status-editor.js',
    'features/pin-group.js',
    'features/likes.js',
    'features/paginator.js',
    'features/album-photos-loader.js',
    'features/audio-upload.js',
    'features/gif-autoplay.js',
    'features/video-audio-coord.js',
    'features/video-delete.js',
];

for (const rel of modules) {
    const abs = path.join(jsRoot, rel);
    if (!fs.existsSync(abs)) {
        console.error(`[vkify16-build] Missing module: ${rel}`);
        process.exit(1);
    }
}

const entryContents = modules.map(rel => `import './${rel}';`).join('\n') + '\n';

const buildOptions = {
    stdin: {
        contents: entryContents,
        resolveDir: jsRoot,
        sourcefile: '_entry.js',
        loader: 'js',
    },
    bundle: true,
    format: 'iife',
    target: 'es2017',
    // Keep identifiers readable; only collapse whitespace and shorten syntax.
    minifyWhitespace: true,
    minifySyntax: true,
    minifyIdentifiers: false,
    keepNames: true,
    sourcemap: true,
    legalComments: 'linked',
    outfile: outFile,
    logLevel: 'info',
    banner: {
        js: '/* VKify16 themepack bundle. Generated by build.mjs. Do not edit by hand. */',
    },
    plugins: [templateHtmlMinify()],
};

const watch = process.argv.includes('--watch');

if (watch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('[vkify16-build] Watching for changes...');
} else {
    await esbuild.build(buildOptions);
    const size = fs.statSync(outFile).size;
    console.log(`[vkify16-build] Wrote ${path.relative(__dirname, outFile)} (${(size / 1024).toFixed(1)} KB)`);
}
